POST http://localhost:3000/getToken
Content-Type: application/json

{
    "username": "user1",
    "password": "password1"
}

###
POST http://localhost:3000/cards/create
Content-Type: application/json
Authorization: Bearer < TOKEN HERE >

{
    "id": 199,
    "name": "Joe Mama",
    "set": "Exlusive Set",
    "type": "Final Boss",
    "power": 1000,
    "toughness": 1000,
    "rarity": "Extremely Rare",
    "cost": 50
}

###
PUT http://localhost:3000/cards/199
Content-Type: application/json
Authorization: Bearer < TOKEN HERE >

{
    "name": "Ultimeatum",
    "set": "Exlusive Set",
    "type": "Final Boss",
    "power": 1000,
    "toughness": 1000,
    "rarity": "Extremely Rare",
    "cost": 50
}